config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  resources :articles
  post '/users', :to => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :link, :date, presence: true
  validates :link, format: URI::regexp(%w[http https])
end

app/models/article_search.rb
class ArticleSearch
  attr_reader :date_from, :date_to

  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], Date.today.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end

  def scope
    Article.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end

  private

  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :email, uniqueness: { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @search = ArticleSearch.new(params[:search])
    @articles = @search.scope.sort_by(&:date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(email: params[:user][:email])
    redirect_to :controller => 'articles', :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1>Hacker News</h1>
<%= form_tag articles_path, method: :get do %>
<p>Вибрати дати: <%= text_field_tag 'search[date_from]', @search.date_from %>
  <%= text_field_tag 'search[date_to]', @search.date_to %></p>
<%= submit_tag 'Search', class: "btn btn-info" %>
  <% end %>

<%= form_tag users_path, method: :post do %>
<p>Отримувати щоденну підбірку новин на пошту: <%= text_field_tag 'user[email]' %>
<%= button_tag 'Додати', class: "edit_button", notice: "Done" %>
<% end %>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Date of addition</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <p><td><%= article.title %></p>
      <p><a href=<%= article.link %>> Читати повністю> </a></p>
      <td><%= article.date %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>